language: php

php:
- 5.6

before_script:
- echo -e "Host *\n\tUserKnownHostsFile=/dev/null\n\tStrictHostKeyChecking no" > /home/travis/.ssh/config
#- echo -e "Host 52.200.159.125\n\tUserKnownHostsFile=/dev/null\n\tStrictHostKeyChecking no" >> /home/travis/.ssh/config


after_success:
- bash .travis/deploy.sh
